### ISSUE TITLE
[Suggestion] Match Rank on the last 3 game

### ISSUE THREAD

**Issue by notBradPitt** [Soneliem/WAIUA#24]
It'd be useful if there's also an indicator for the overall rank in the past 3 matches for each player. For example, someone who won the past 3 matches as MVPs is an obvious indicator of smurfing

**Comment by Soneliem** [comment]
Do you mean the position on the leaderboard? If so I'll have to take a look if that info is even available.

**Comment by 7atem60010** [comment]
I second that, the rank in the leaderboard of last 3 games is really important

**Comment by notBradPitt** [comment]
> Do you mean the position on the leaderboard? If so I'll have to take a look if that info is even available.

I think there's a "score" value under the "stats" of each player when you fetch a match on the Valorant API, if that's what you're using. There are categories for all players or for each team so you can get both team and match rank.

**Comment by notBradPitt** [comment]
![image](https://user-images.githubusercontent.com/85218180/146699214-d33dc644-ee7c-43af-8a88-2edd4566ead7.png)
On the API that I use

**Comment by 7atem60010** [comment]
Yes, then you have to sort there scores and see what is the rank of the
specified player.

**Comment by Soneliem** [comment]
@notBradPitt  think your last point there pretty much is the issue. For each match you'll need to query everyone's score and check which of them is the player. Then we'll have to so that for all three games so that's about 6 operations and 3 API requests. And that's just one player, for 10 players its 60 operations and 30 API requests just to get three numbers per person.  That's also why I said no to adding an average KDA. 

Additionally I want to bring up the [bullying aspect](https://www.reddit.com/r/VALORANT/comments/rij2ey/how_do_people_see_my_rank_midgame/) to this as knowing of a team/enemy was bottom fragging or underperforming is an easy target method. I have to allow the app to help spot smurfs without making it an easy avenue of hate for toxic players.

However, I've investigating new methods and ideas so maybe this is a possibility in the future. Hope you understand and If you have any other ideas or suggestions please don't hesitate to provide them although my [discord](https://discord.gg/X7CYCeZSRK) will be perfect for that.
