### ISSUE TITLE
I also got banned permanently using this

### ISSUE THREAD

**Issue by bugwheels94** [Soneliem/WAIUA#30]
I wasted my money coz I had skins. Riot games is a bad company and I learned it the hard way. No warning nothing just banned. I also have open-source software so I know that it was my choice to use it and I also know that this software looks completely safe. But as I said Riot Games and Vanguard are not as great as they think of themselves to be. Never buying from anyone who can ban me and I have no legal rights against sigh.

**Comment by Soneliem** [comment]
Interesting tangent about Riot Games but yeah, never spend money on a game you can't get back. 
As for my app, you were probably caught in a ban wave. There are no warning or anything as hackers would stop using tools that were flagged. If you truly are not cheating you will be able to argue against the ban (if it even happened) and get unbanned. False positives are quite rare but people that say they're banned because of one all seem to claim that an app like mine was the cause of it.

**Comment by bugwheels94** [comment]
Just leaving an update here...

They never even listened let alone unban me. I upgraded from RX580 to RTX3080 and monitor from acer 144hz to MSI MAG251RX and ryzen 1600 to 5600 on the same day and went from gold2 to plat 3 without even losing a single game as much as I remember. 
As I said there devs are so mediocre and they probably think that tenz is same good on all devices so they did not consider this but we all know that devices make huge impact on gaming and not everything is skills.

So, just a warning there...if you upgrade the devices like I did then maybe slow down because of val's not well thought of anti cheat

Nobody will trust me I know but Valorant bans innocent people in their self righteousness and never listens to them...Innocent until proven guilty is what makes law but obv valorant is not moral but pretends to... Adding invoices though i know nobody will trust me and support Valorant robbing innocent people so **watch out**
![cpu](https://user-images.githubusercontent.com/4629859/161421356-55ed4b4f-6945-4329-9da0-6b9e1085052f.png)
![GPU](https://user-images.githubusercontent.com/4629859/161421358-a93cb714-c426-44b4-9c42-84010a762e60.png)
![monitor](https://user-images.githubusercontent.com/4629859/161421359-510e5547-0294-4dc3-93cc-5c1b71bffea8.png)
