### ISSUE TITLE
Installed ver1.4.0.2 still showing to update it to the same version

### ISSUE THREAD

**Issue by Rushabh-C** [Soneliem/WAIUA#38]
I updated to the newest version of WAIUA which is Ver1.4.0.2 and still shows that I'm on previous version 1.4.0.1 and gives me pop up to update to the new version. Please look into it. It is happening closing it & upon reopening the new version it will gives this.

**Comment by Soneliem** [comment]
Might know why this is happening:
Go to C:\Program Files\WAIUA and let me know / screenshot what you see. 

If there are 2 uninstallers, please try uninstalling both.

**Comment by physanus** [comment]
It's happening for me, too. I had v 1.4.0.1 installed and upgraded via the in-app installer: https://i.imgur.com/b3udVVt.png
The issue was that during the installation of v 1.4.0.2 the program (and start menu entry) of v 1.4.0.1 did not get removed. A manual uninstall under `Control Panel > Programs and Features > Waiua version 1.4.0.1` fixed it. 
That kinda seems like a minor version upgrade instead of a patch release, tho

**Comment by Soneliem** [comment]
The lack of 2 uninstallers there is quite weird. In the last update I had to create a new installer configuration file because I seem to have lost the old one. Something must have changed but I don't think I can fix it. 
I guess the solution is to uninstall all versions of WAIUA and then installing the latest one.

**Comment by physanus** [comment]
Well, I actually had no files at all in `C:\Program Files\WAIUA` prior to the update. I'm not sure but I guess it was installed in appdata or something?
I'm no C# programmer and I've never made a Windows installer, but wouldn't the best solution be to run the old uninstaller automatically once the current/new installer finished? That way, also people on v1.4.0.1 could upgrade to v1.4.0.z without having to manually do anything. You would have to release a new version tho.

**Comment by Rushabh-C** [comment]
Well I missed somehow that i installed the previous version on other Drive instead of Default by which the issue was there. But now I changed it & it works fine for me. Sorry for misconception.

**Comment by physanus** [comment]
Since this is an issue for all users of WAIUA (afaik), I don't think this should be closed yet

**Comment by Soneliem** [comment]
Alright, I did more testing and I found the real issue, it was because the old version allowed installing to AppData or ProgramFiles. I accidentally configured the new version to be ProgramFiles only (admin required). As this only affects new users, I will just update the installer file.

**Comment by physanus** [comment]
Sounds great, thanks!

One more thing: I assume WAIUA was previously installed to AppData by default (even if not, we should assume people did install it there in the past). Due to the auto-updater installing the update to ProgramFiles, they currently have both versions installed (a friend of mine had the same issue). 
WAIUA should work fine again after you released the fixes you mentioned, but that changes nothing about it actually being installed twice. Maybe it'd be possible to check for both installations being present (during startup, could be an easy 'if-folder-is-present') and then tell the user to uninstall one version manually/maybe even automatically remove it so the user does not have to do anything on their own
