### ISSUE TITLE
Incorrect weapon name

### ISSUE THREAD

**Issue by SuperS123** [Soneliem/WAIUA#50]
![image](https://user-images.githubusercontent.com/57376381/184430302-d7dc18ed-243a-4470-b632-facdb56c2b35.png)

**Comment by Soneliem** [comment]
Weirdness from https://valorant-api.com. This is the entry for the skin:
`displayName":"Hue Shift Spectre","displayIcon":null,"fullRender":"https://media.valorant-api.com/weaponskinchromas/3948f41b-4239-40b6-5a04-6ba0202a0ce0/fullrender.png"`

Since they set the data directly from the game, it is probably an issue from Riot's side or val-api. Can't really fix it.
